version: '3.8'
services:
  netmgmt-chatops:
    image: netmgmtchatops:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
