version: '3.8'
services:
  netmgmt-chatops:
    image: ${DOCKERHUB_USERNAME}/netmgmtchatops:latest
    ports:
      - "8000:8000"
    environment:
      WEBEX_BOT_TOKEN: ${WEBEX_BOT_TOKEN}
      RESTCONF_USERNAME: ${RESTCONF_USERNAME}
      RESTCONF_PASSWORD: ${RESTCONF_PASSWORD}
      DEVICE_IP_PORT: ${DEVICE_IP_PORT}
      DEBUG_NETOPS: 1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
