name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      DOCKER_IMAGE_NAME: netmgmtchatops
      SERVICE_NAME: netmgmt-chatops

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Pull the latest Docker image
        run: | 
          echo ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check that docker-compose.yml is valid
        run: |
          sudo docker-compose -f docker-compose.yml config

      - name: Create .env file with secrets
        run: |
          echo WEBEX_BOT_TOKEN=${{ secrets.WEBEX_BOT_TOKEN }} >> .env
          echo RESTCONF_USERNAME=${{ secrets.RESTCONF_USERNAME }} >> .env
          echo RESTCONF_PASSWORD=${{ secrets.RESTCONF_PASSWORD }} >> .env
          echo DEVICE_IP_PORT=${{ secrets.DEVICE_IP_PORT }} >> .env

      - name: Update docker swarm service
        run: |
          docker stack deploy --compose-file docker-compose.yml ${{ env.SERVICE_NAME }}
