name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, trexnew]
    env:
      DOCKER_IMAGE_NAME: netmgmtchatops

    steps:
      - name: Pull the latest Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Check if /opt/netmgmt-chatops directory exists
        run: |
          if [ ! -d /opt/netmgmt-chatops ]; then
            sudo mkdir -p /opt/netmgmt-chatops
          fi

      - name: Check if docker-compose.yml exists
        id: check_docker_compose
        run: |
          if [ -f /opt/netmgmt-chatops/docker-compose.yml ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Download docker-compose.yml from GitHub repo
        if: steps.check_docker_compose.outputs.exists == 'false'
        run: |
          # Download the docker-compose.yml file
          # Use the github context variables to get the URL of the docker-compose.yml file in the current repository
          # Note: This assumes the file is publicly accessible, otherwise you need to authenticate the request
          sudo curl -L https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml -o /opt/netmgmt-chatops/docker-compose.yml

      - name: Deploy to production server
        run: |
          # Update the Docker Swarm service
          sudo docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest netmgmt-chatops
