name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: [self-hosted && trexnew]
    steps:
    - name: Authenticate with Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull the latest Docker image
      run: docker pull your-dockerhub-username/your-image:latest

    - name: Deploy to production server
      run: |
        # Update the Docker Swarm service
        docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest netmgmt-chatops